spring.application.name=mapuescuela-api

# flowable.external.worker.rest.base-url=https://trial.flowable.com
# flowable.external.worker.rest.context-path=/external-job-api
flowable.external.worker.rest.authentication.bearer.token=${FLOWABLE_TOKEN}
spring.jersey.type=filter